main:
  epochs: 200
  batch_size: 32
  lr: 2.0e-4           
  weight_decay: 1.0e-4
  clip_grad: 0.5
  amp: true
  seed: 42
  patience: 80         
  out_dir: outputs/pretrain_breast_triplet_semihard
  data_root: "data/processed/breast"
  proto_warmup: 1       
  sched: "plateau"    
  lr_patience: 15
  min_lr: 1.0e-8
  select_metric: mcc 

model:
  node_dim: 13
  enc_hid: 64
  enc_out: 64
  num_heads: 4
  embed_dim: 128
  num_classes: 2
  metric_gamma: 22      

contrastive:
  method: "triplet_semihard"
  weight: 0.02           
  margin: 0.35          
  tau: 1.0

data:
  split_ratios: [0.6, 0.2, 0.2]   
  stratify: false                    
  include_unknown_in_split: false   
  keep_unknown: false                
  num_workers: 0                  
